name: Lint, Test, Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.6', '3.7', '3.8' ]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Linting
      run: |
          pip install pylint
          python -m pylint --reports=n --rcfile=.pylintrc certbot_dns_hetzner
    - name: Testing with tox
      run: |
        pip install tox tox-gh-actions
        tox
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true